---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: timber-frontend
  name: timber-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: timber-frontend
  type: NodePort
  env:
  - name: TIMBER_BACKEND_API_URL
    value: 35.240.97.87:30288
  
